version: '3'
services:
  mysql:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password --max_allowed_packet=256M"
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./config/mysql:/etc/mysql/conf.d"
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  phpmyadmin:
    #image: bitnami/phpmyadmin:5.0.2-debian-10-r72
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
      #- 8443:443
    environment:
        DATABASE_HOST: mysql
    restart: always 
    links:
     - mysql


# docker stack deploy -c mysql.yml mysql